### ISSUE TITLE
Native Keyboard UI pops up when selecting cells in Mobile web

### ISSUE THREAD

**Issue by gurgus0189** [nhnent/tui.grid#266]
모바일 웹뷰를 통해 grid를 보여주고 있습니다.

모바일에서 셀 선택시 키보드가 위로 올라오는데 제거 하는 방법이 있을까요?

api를 보고 있는데 그런 속성을 못찾겠네요..

---

> 이슈 관리 정책상 제목과 본문을 영문으로 수정합니다. 양해 부탁드립니다.

## English

I'm using the Grid in mobile web, but whenever I select a cell, the native keyboard UI pops up. 
Is there any way to get around this issue?

**Comment by dongwoo-kim** [comment]
This is a known issue. TOAST UI Grid does not officially support mobile environment yet. This happens because the Grid is using a hidden `textarea` element to offer clipboard-copy functionality when users press `ctrl + c` in Internet Explorer.

We are planning to handle this issue after the major update for 4.0.0, but it may take few months.

**Comment by jung-han** [comment]
@gurgus0189 Fixed in v3.7.0
